### ISSUE TITLE
Come back task list

### ISSUE THREAD

**Issue by zafarali** [zafarali/metastasis#94]
## cc3d task list
- [ ] Go through CC3D code
- [ ] check logic for divisions etc
- [ ] check statistics calculator
- [ ] run tests
- [ ] generate new data for graphs

## spaceless task list
- [ ] Go through code
- [ ] check logic for divisions etc
- [ ] check statistics calculator
- [ ] run tests
- [ ] generate new data for graphs

**Comment by zafarali** [comment]
why is this hardcoded?
https://github.com/zafarali/metastasis/blob/spaceless/spaceless/Model.py#L371

**Comment by zafarali** [comment]
- found issue in cc3d sampling scheme
- fixed, now need to re-run the models
